### PR TITLE
Added a Makefile to streamline the packaging process

### PR DESCRIPTION
**Pull request by ilent2**
Added a Makefile to create the new DAP using git archive.  Makefile extracts version/name information from meta.yaml file.

### CODE REVIEW

**Comment by bkabrda** [comment]
Thanks for this PR. A question: would it make more sense to implement this functionality as a "tweak" assistant in https://github.com/devassistant/dap-dap? dap-dap is a package that deals with kickstarting and working with DAPs and I think this is a functionality that belongs there. Also, everyone would then be able to use that functionality on any DAP - we wouldn't need to add a Makefile like this to repos with DAP code, which would be awesome.

**Comment by hroncok** [comment]
Makefile is nice, however, there is a way to build a dap already. It is:

`da tweak dap pack`

It has also ability to ignore files based on .dapignore.

**Comment by ilent2** [comment]
Cool, I wasn't aware of that tweak.  I suppose I should have paid more attention to the documentation.

**Comment by hroncok** [comment]
Or maybe we could do more to promote it?

**Pull request closed without merging**
